/**
 * Arachne Memory Notebook — a dedicated Notion page hierarchy for storing
 * curated knowledge, task context, secrets references, and agent notes.
 */

import {
  searchPages,
  getPage,
  getPageBlocks,
  createPage,
  appendBlocks,
  extractTitle,
  blocksToText,
  richTextToPlain,
} from "./client"
import type { NotionPage, NotionBlock } from "./types"
import { loadIntegrations, saveIntegrations } from "./integrations"

const NOTEBOOK_TITLE = "Arachne Memory"

// ------------------------------------------------------------------
// Rich text / block helpers
// ------------------------------------------------------------------

function textBlock(text: string, type: "paragraph" | "heading_1" | "heading_2" | "heading_3" = "paragraph") {
  return {
    object: "block" as const,
    type,
    [type]: {
      rich_text: [{ type: "text" as const, text: { content: text } }],
    },
  }
}

function titleProperty(title: string) {
  return {
    title: [{ text: { content: title } }],
  }
}

// ------------------------------------------------------------------
// Ensure the root memory notebook exists
// ------------------------------------------------------------------

export async function ensureMemoryNotebook(token: string): Promise<string> {
  // Check cached ID first
  const integrations = loadIntegrations()
  const cachedId = integrations.notion?.memoryNotebookPageId

  if (cachedId) {
    // Verify it still exists
    const check = await getPage(token, cachedId)
    if (check.ok && !(check.data as NotionPage & { archived?: boolean }).archived) {
      return cachedId
    }
  }

  // Search for existing notebook
  const search = await searchPages(token, NOTEBOOK_TITLE, { filter: "page", pageSize: 5 })
  if (search.ok) {
    for (const result of search.data.results) {
      if (result.object === "page") {
        const page = result as NotionPage
        const pageTitle = extractTitle(page)
        if (pageTitle === NOTEBOOK_TITLE && !(page as NotionPage & { archived?: boolean }).archived) {
          // Found it — cache and return
          if (integrations.notion) {
            integrations.notion.memoryNotebookPageId = page.id
            saveIntegrations(integrations)
          }
          return page.id
        }
      }
    }
  }

  // Create new notebook
  const result = await createPage(
    token,
    { page_id: "" }, // workspace-level — will be overridden by Notion API for root pages
    { title: titleProperty(NOTEBOOK_TITLE) },
    [
      textBlock("Arachne Memory Notebook", "heading_1"),
      textBlock(
        "This notebook is maintained by Arachne to store curated knowledge, task context, and agent notes. " +
        "Sub-pages are created automatically for specific topics and tasks.",
      ),
      textBlock("Table of Contents", "heading_2"),
      textBlock("(auto-generated by maintenance task)"),
    ],
  )

  if (!result.ok) {
    throw new Error(`Failed to create memory notebook: ${result.error}`)
  }

  // Cache the page ID
  if (integrations.notion) {
    integrations.notion.memoryNotebookPageId = result.data.id
    saveIntegrations(integrations)
  }

  return result.data.id
}

// ------------------------------------------------------------------
// Sub-page operations
// ------------------------------------------------------------------

export async function createMemoryPage(
  token: string,
  rootId: string,
  title: string,
  content: string,
): Promise<{ id: string; title: string }> {
  const blocks = content.split("\n\n").filter(Boolean).map((para) => textBlock(para))

  const result = await createPage(
    token,
    { page_id: rootId },
    { title: titleProperty(title) },
    blocks,
  )

  if (!result.ok) {
    throw new Error(`Failed to create memory page "${title}": ${result.error}`)
  }

  return { id: result.data.id, title }
}

export interface MemoryPageSummary {
  id: string
  title: string
  lastEdited: string
}

export async function listMemoryPages(
  token: string,
  rootId: string,
): Promise<MemoryPageSummary[]> {
  const result = await getPageBlocks(token, rootId)
  if (!result.ok) {
    throw new Error(`Failed to list memory pages: ${result.error}`)
  }

  const pages: MemoryPageSummary[] = []

  for (const block of result.data.results) {
    if (block.type === "child_page") {
      const childData = block[block.type] as { title?: string } | undefined
      pages.push({
        id: block.id,
        title: childData?.title ?? "Untitled",
        lastEdited: block.last_edited_time ?? "",
      })
    }
  }

  return pages
}

export async function readMemoryPage(
  token: string,
  pageId: string,
): Promise<{ title: string; content: string }> {
  const page = await getPage(token, pageId)
  if (!page.ok) {
    throw new Error(`Failed to read page: ${page.error}`)
  }

  const title = extractTitle(page.data)

  // Collect all blocks (paginated)
  const allBlocks: NotionBlock[] = []
  let cursor: string | undefined

  do {
    const blocksResult = await getPageBlocks(token, pageId, cursor)
    if (!blocksResult.ok) break
    allBlocks.push(...blocksResult.data.results)
    cursor = blocksResult.data.has_more ? blocksResult.data.next_cursor ?? undefined : undefined
  } while (cursor)

  return { title, content: blocksToText(allBlocks) }
}

// ------------------------------------------------------------------
// Consolidation / maintenance
// ------------------------------------------------------------------

export interface ConsolidationResult {
  pagesScanned: number
  merged: number
  archived: number
}

export async function consolidateNotebook(
  token: string,
  rootId: string,
): Promise<ConsolidationResult> {
  const pages = await listMemoryPages(token, rootId)
  const result: ConsolidationResult = { pagesScanned: pages.length, merged: 0, archived: 0 }

  // Group by normalized title for duplicate detection
  const titleGroups = new Map<string, MemoryPageSummary[]>()
  for (const page of pages) {
    const key = page.title.toLowerCase().trim()
    const group = titleGroups.get(key) ?? []
    group.push(page)
    titleGroups.set(key, group)
  }

  // Merge duplicates (keep the newest, append content from older ones)
  for (const [, group] of titleGroups) {
    if (group.length <= 1) continue

    // Sort by last edited descending — keep newest
    group.sort((a, b) => new Date(b.lastEdited).getTime() - new Date(a.lastEdited).getTime())
    const [keeper, ...dupes] = group

    for (const dupe of dupes) {
      try {
        const dupeContent = await readMemoryPage(token, dupe.id)
        if (dupeContent.content.trim()) {
          // Append dupe content to keeper
          await appendBlocks(token, keeper.id, [
            textBlock(`--- Merged from duplicate "${dupe.title}" ---`, "heading_3"),
            ...dupeContent.content.split("\n\n").filter(Boolean).map((p) => textBlock(p)),
          ])
        }
        // Archive the duplicate
        await archivePage(token, dupe.id)
        result.merged++
      } catch {
        // Skip failed merges
      }
    }
  }

  // Archive stale pages (no edits in 30+ days)
  const thirtyDaysAgo = Date.now() - 30 * 24 * 60 * 60 * 1000
  for (const page of pages) {
    if (!page.lastEdited) continue
    const edited = new Date(page.lastEdited).getTime()
    if (edited < thirtyDaysAgo) {
      // Don't archive pages we already merged/archived above
      const normalizedTitle = page.title.toLowerCase().trim()
      const group = titleGroups.get(normalizedTitle) ?? []
      if (group.length > 1 && group[0].id !== page.id) continue // already handled as dupe

      try {
        await archivePage(token, page.id)
        result.archived++
      } catch {
        // Skip
      }
    }
  }

  // Rebuild table of contents
  await rebuildTableOfContents(token, rootId)

  return result
}

async function archivePage(token: string, pageId: string): Promise<void> {
  const response = await fetch(`https://api.notion.com/v1/pages/${pageId}`, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "Notion-Version": "2022-06-28",
    },
    body: JSON.stringify({ archived: true }),
  })

  if (!response.ok) {
    throw new Error(`Failed to archive page ${pageId}`)
  }
}

async function rebuildTableOfContents(
  token: string,
  rootId: string,
): Promise<void> {
  const pages = await listMemoryPages(token, rootId)

  if (pages.length === 0) return

  const tocLines = pages.map((p) => `- ${p.title} (last edited: ${p.lastEdited ? new Date(p.lastEdited).toLocaleDateString() : "unknown"})`)

  // Append a refreshed ToC section
  await appendBlocks(token, rootId, [
    textBlock("---"),
    textBlock("Table of Contents (auto-updated)", "heading_2"),
    ...tocLines.map((line) => textBlock(line)),
    textBlock(`Last updated: ${new Date().toISOString()}`),
  ])
}
